
spring.datasource.url=jdbc:mysql://localhost:3306/licenta_db
spring.datasource.username=root
spring.datasource.password=admin

# The "Dialect" tells Spring Data JPA how to speak MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional but recommended
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081